# Generated by Django 5.0 on 2024-02-06 23:31

import django_cryptography.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('sensitive_data', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
