# Generated by Django 5.0 on 2024-02-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messageroom_room_name_messageroom_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageroom',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messageroom',
            name='user2',
        ),
    ]
