# Generated by Django 5.0 on 2024-02-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_rename_user_messageroom_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='messageroom',
            name='is_group',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
