# Generated by Django 5.0 on 2024-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_roommessage_options_messageroom_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
