# Generated by Django 5.0 on 2023-12-23 20:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('thumbnail', models.ImageField(default=None, upload_to='job-thumbnail')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(default=None, max_length=5000)),
                ('requirements', models.TextField(default=None, max_length=5000)),
                ('company_name', models.CharField(db_index=True, default=None, max_length=150)),
                ('minimum_experience', models.PositiveIntegerField(blank=True, default=0)),
                ('job_type', models.CharField(blank=True, default='Full Time', max_length=100)),
                ('looking_position', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=50)),
                ('state', models.CharField(blank=True, db_index=True, max_length=50)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')])),
                ('language', models.CharField(blank=True, default='English', max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=65)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('keywords', models.CharField(blank=True, db_index=True, max_length=200)),
                ('last_date_of_apply', models.DateField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_applications', to='hr.jobpost')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
