# Generated by Django 5.0 on 2023-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_jobpost_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon',
            field=models.ImageField(default='', upload_to='category-img'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
