# Generated by Django 5.0 on 2023-12-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_jobcategory_icon_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.ImageField(upload_to='category-img'),
        ),
    ]
