# Generated by Django 5.0 on 2023-12-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_jobcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
