# Generated by Django 5.0 on 2023-12-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_jobcategory_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
