# Generated by Django 5.0 on 2024-01-03 07:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='requirements',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None, max_length=5000),
        ),
    ]
