# Generated by Django 5.0 on 2023-12-31 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
        ('hr', '0014_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='hrprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='hrprofile',
            name='company',
            field=models.OneToOneField(blank=True, default='46821c24-d5d6-4d40-b426-3aebcfcedc85', on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
        ),
    ]
