# Generated by Django 5.0 on 2023-12-31 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_candidateprofile_full_name_and_more'),
        ('hr', '0014_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrprofile',
            name='company',
            field=models.ForeignKey(blank=True, default='46821c24-d5d6-4d40-b426-3aebcfcedc85', on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
        ),
    ]
