# Generated by Django 5.0 on 2023-12-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportcontact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='supportcontact',
            name='last_name',
        ),
    ]
