# Generated by Django 5.0 on 2023-12-23 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_first_name_supportcontact_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcontact',
            name='phone_number',
            field=models.CharField(default=8801632398271, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
