# Generated by Django 5.0 on 2024-01-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
