# Generated by Django 5.0 on 2024-01-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
