# Generated by Django 5.0 on 2024-01-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_remove_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='comment',
        ),
    ]
