# Generated by Django 5.0 on 2024-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_alter_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=100),
        ),
    ]
