# Generated by Django 5.0 on 2024-01-03 07:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_alter_blogpost_content_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=6000),
        ),
    ]
